// Generated by gencpp from file basic_sensor_interface/joint_sns.msg
// DO NOT EDIT!


#ifndef BASIC_SENSOR_INTERFACE_MESSAGE_JOINT_SNS_H
#define BASIC_SENSOR_INTERFACE_MESSAGE_JOINT_SNS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic_sensor_interface
{
template <class ContainerAllocator>
struct joint_sns_
{
  typedef joint_sns_<ContainerAllocator> Type;

  joint_sns_()
    : prox1(0)
    , dist1(0)
    , prox2(0)
    , dist2(0)
    , prox3(0)
    , dist3(0)  {
    }
  joint_sns_(const ContainerAllocator& _alloc)
    : prox1(0)
    , dist1(0)
    , prox2(0)
    , dist2(0)
    , prox3(0)
    , dist3(0)  {
  (void)_alloc;
    }



   typedef uint32_t _prox1_type;
  _prox1_type prox1;

   typedef uint32_t _dist1_type;
  _dist1_type dist1;

   typedef uint32_t _prox2_type;
  _prox2_type prox2;

   typedef uint32_t _dist2_type;
  _dist2_type dist2;

   typedef uint32_t _prox3_type;
  _prox3_type prox3;

   typedef uint32_t _dist3_type;
  _dist3_type dist3;





  typedef boost::shared_ptr< ::basic_sensor_interface::joint_sns_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic_sensor_interface::joint_sns_<ContainerAllocator> const> ConstPtr;

}; // struct joint_sns_

typedef ::basic_sensor_interface::joint_sns_<std::allocator<void> > joint_sns;

typedef boost::shared_ptr< ::basic_sensor_interface::joint_sns > joint_snsPtr;
typedef boost::shared_ptr< ::basic_sensor_interface::joint_sns const> joint_snsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic_sensor_interface::joint_sns_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basic_sensor_interface::joint_sns_<ContainerAllocator1> & lhs, const ::basic_sensor_interface::joint_sns_<ContainerAllocator2> & rhs)
{
  return lhs.prox1 == rhs.prox1 &&
    lhs.dist1 == rhs.dist1 &&
    lhs.prox2 == rhs.prox2 &&
    lhs.dist2 == rhs.dist2 &&
    lhs.prox3 == rhs.prox3 &&
    lhs.dist3 == rhs.dist3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basic_sensor_interface::joint_sns_<ContainerAllocator1> & lhs, const ::basic_sensor_interface::joint_sns_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basic_sensor_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_sensor_interface::joint_sns_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_sensor_interface::joint_sns_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_sensor_interface::joint_sns_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0370817355f4d293f185fcd9ba10ba17";
  }

  static const char* value(const ::basic_sensor_interface::joint_sns_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0370817355f4d293ULL;
  static const uint64_t static_value2 = 0xf185fcd9ba10ba17ULL;
};

template<class ContainerAllocator>
struct DataType< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic_sensor_interface/joint_sns";
  }

  static const char* value(const ::basic_sensor_interface::joint_sns_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 prox1\n"
"uint32 dist1\n"
"uint32 prox2\n"
"uint32 dist2\n"
"uint32 prox3\n"
"uint32 dist3\n"
;
  }

  static const char* value(const ::basic_sensor_interface::joint_sns_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prox1);
      stream.next(m.dist1);
      stream.next(m.prox2);
      stream.next(m.dist2);
      stream.next(m.prox3);
      stream.next(m.dist3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_sns_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic_sensor_interface::joint_sns_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic_sensor_interface::joint_sns_<ContainerAllocator>& v)
  {
    s << indent << "prox1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.prox1);
    s << indent << "dist1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dist1);
    s << indent << "prox2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.prox2);
    s << indent << "dist2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dist2);
    s << indent << "prox3: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.prox3);
    s << indent << "dist3: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dist3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_SENSOR_INTERFACE_MESSAGE_JOINT_SNS_H
