; Auto-generated. Do not edit!


(cl:in-package tae_psoc-msg)


;//! \htmlinclude SensorPacket.msg.html

(cl:defclass <SensorPacket> (roslisp-msg-protocol:ros-message)
  ((sns_1_FFT_NS
    :reader sns_1_FFT_NS
    :initarg :sns_1_FFT_NS
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (sns_1_FFT_WE
    :reader sns_1_FFT_WE
    :initarg :sns_1_FFT_WE
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (sns_1_4Ch
    :reader sns_1_4Ch
    :initarg :sns_1_4Ch
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (sns_1_F_M
    :reader sns_1_F_M
    :initarg :sns_1_F_M
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (sns_2_FFT_NS
    :reader sns_2_FFT_NS
    :initarg :sns_2_FFT_NS
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (sns_2_FFT_WE
    :reader sns_2_FFT_WE
    :initarg :sns_2_FFT_WE
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (sns_2_4Ch
    :reader sns_2_4Ch
    :initarg :sns_2_4Ch
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (sns_2_F_M
    :reader sns_2_F_M
    :initarg :sns_2_F_M
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (sns1_vorticity
    :reader sns1_vorticity
    :initarg :sns1_vorticity
    :type cl:float
    :initform 0.0)
   (sns2_vorticity
    :reader sns2_vorticity
    :initarg :sns2_vorticity
    :type cl:float
    :initform 0.0))
)

(cl:defclass SensorPacket (<SensorPacket>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SensorPacket>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SensorPacket)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tae_psoc-msg:<SensorPacket> is deprecated: use tae_psoc-msg:SensorPacket instead.")))

(cl:ensure-generic-function 'sns_1_FFT_NS-val :lambda-list '(m))
(cl:defmethod sns_1_FFT_NS-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_1_FFT_NS-val is deprecated.  Use tae_psoc-msg:sns_1_FFT_NS instead.")
  (sns_1_FFT_NS m))

(cl:ensure-generic-function 'sns_1_FFT_WE-val :lambda-list '(m))
(cl:defmethod sns_1_FFT_WE-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_1_FFT_WE-val is deprecated.  Use tae_psoc-msg:sns_1_FFT_WE instead.")
  (sns_1_FFT_WE m))

(cl:ensure-generic-function 'sns_1_4Ch-val :lambda-list '(m))
(cl:defmethod sns_1_4Ch-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_1_4Ch-val is deprecated.  Use tae_psoc-msg:sns_1_4Ch instead.")
  (sns_1_4Ch m))

(cl:ensure-generic-function 'sns_1_F_M-val :lambda-list '(m))
(cl:defmethod sns_1_F_M-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_1_F_M-val is deprecated.  Use tae_psoc-msg:sns_1_F_M instead.")
  (sns_1_F_M m))

(cl:ensure-generic-function 'sns_2_FFT_NS-val :lambda-list '(m))
(cl:defmethod sns_2_FFT_NS-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_2_FFT_NS-val is deprecated.  Use tae_psoc-msg:sns_2_FFT_NS instead.")
  (sns_2_FFT_NS m))

(cl:ensure-generic-function 'sns_2_FFT_WE-val :lambda-list '(m))
(cl:defmethod sns_2_FFT_WE-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_2_FFT_WE-val is deprecated.  Use tae_psoc-msg:sns_2_FFT_WE instead.")
  (sns_2_FFT_WE m))

(cl:ensure-generic-function 'sns_2_4Ch-val :lambda-list '(m))
(cl:defmethod sns_2_4Ch-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_2_4Ch-val is deprecated.  Use tae_psoc-msg:sns_2_4Ch instead.")
  (sns_2_4Ch m))

(cl:ensure-generic-function 'sns_2_F_M-val :lambda-list '(m))
(cl:defmethod sns_2_F_M-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns_2_F_M-val is deprecated.  Use tae_psoc-msg:sns_2_F_M instead.")
  (sns_2_F_M m))

(cl:ensure-generic-function 'sns1_vorticity-val :lambda-list '(m))
(cl:defmethod sns1_vorticity-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns1_vorticity-val is deprecated.  Use tae_psoc-msg:sns1_vorticity instead.")
  (sns1_vorticity m))

(cl:ensure-generic-function 'sns2_vorticity-val :lambda-list '(m))
(cl:defmethod sns2_vorticity-val ((m <SensorPacket>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tae_psoc-msg:sns2_vorticity-val is deprecated.  Use tae_psoc-msg:sns2_vorticity instead.")
  (sns2_vorticity m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SensorPacket>) ostream)
  "Serializes a message object of type '<SensorPacket>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_1_FFT_NS))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream))
   (cl:slot-value msg 'sns_1_FFT_NS))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_1_FFT_WE))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream))
   (cl:slot-value msg 'sns_1_FFT_WE))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_1_4Ch))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    ))
   (cl:slot-value msg 'sns_1_4Ch))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_1_F_M))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'sns_1_F_M))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_2_FFT_NS))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream))
   (cl:slot-value msg 'sns_2_FFT_NS))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_2_FFT_WE))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream))
   (cl:slot-value msg 'sns_2_FFT_WE))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_2_4Ch))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    ))
   (cl:slot-value msg 'sns_2_4Ch))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sns_2_F_M))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'sns_2_F_M))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'sns1_vorticity))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'sns2_vorticity))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SensorPacket>) istream)
  "Deserializes a message object of type '<SensorPacket>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_1_FFT_NS) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_1_FFT_NS)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_1_FFT_WE) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_1_FFT_WE)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_1_4Ch) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_1_4Ch)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_1_F_M) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_1_F_M)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_2_FFT_NS) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_2_FFT_NS)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_2_FFT_WE) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_2_FFT_WE)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_2_4Ch) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_2_4Ch)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sns_2_F_M) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sns_2_F_M)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'sns1_vorticity) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'sns2_vorticity) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SensorPacket>)))
  "Returns string type for a message object of type '<SensorPacket>"
  "tae_psoc/SensorPacket")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SensorPacket)))
  "Returns string type for a message object of type 'SensorPacket"
  "tae_psoc/SensorPacket")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SensorPacket>)))
  "Returns md5sum for a message object of type '<SensorPacket>"
  "b42cd8856cf6ff4337fc1ed6207fb9c0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SensorPacket)))
  "Returns md5sum for a message object of type 'SensorPacket"
  "b42cd8856cf6ff4337fc1ed6207fb9c0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SensorPacket>)))
  "Returns full string definition for message of type '<SensorPacket>"
  (cl:format cl:nil "uint16[] sns_1_FFT_NS~%uint16[] sns_1_FFT_WE~%int16[] sns_1_4Ch~%float32[] sns_1_F_M~%uint16[] sns_2_FFT_NS~%uint16[] sns_2_FFT_WE~%int16[] sns_2_4Ch~%float32[] sns_2_F_M~%float32 sns1_vorticity~%float32 sns2_vorticity~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SensorPacket)))
  "Returns full string definition for message of type 'SensorPacket"
  (cl:format cl:nil "uint16[] sns_1_FFT_NS~%uint16[] sns_1_FFT_WE~%int16[] sns_1_4Ch~%float32[] sns_1_F_M~%uint16[] sns_2_FFT_NS~%uint16[] sns_2_FFT_WE~%int16[] sns_2_4Ch~%float32[] sns_2_F_M~%float32 sns1_vorticity~%float32 sns2_vorticity~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SensorPacket>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_1_FFT_NS) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_1_FFT_WE) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_1_4Ch) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_1_F_M) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_2_FFT_NS) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_2_FFT_WE) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_2_4Ch) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sns_2_F_M) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SensorPacket>))
  "Converts a ROS message object to a list"
  (cl:list 'SensorPacket
    (cl:cons ':sns_1_FFT_NS (sns_1_FFT_NS msg))
    (cl:cons ':sns_1_FFT_WE (sns_1_FFT_WE msg))
    (cl:cons ':sns_1_4Ch (sns_1_4Ch msg))
    (cl:cons ':sns_1_F_M (sns_1_F_M msg))
    (cl:cons ':sns_2_FFT_NS (sns_2_FFT_NS msg))
    (cl:cons ':sns_2_FFT_WE (sns_2_FFT_WE msg))
    (cl:cons ':sns_2_4Ch (sns_2_4Ch msg))
    (cl:cons ':sns_2_F_M (sns_2_F_M msg))
    (cl:cons ':sns1_vorticity (sns1_vorticity msg))
    (cl:cons ':sns2_vorticity (sns2_vorticity msg))
))
