// Generated by gencpp from file tae_psoc/SensorPacket.msg
// DO NOT EDIT!


#ifndef TAE_PSOC_MESSAGE_SENSORPACKET_H
#define TAE_PSOC_MESSAGE_SENSORPACKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tae_psoc
{
template <class ContainerAllocator>
struct SensorPacket_
{
  typedef SensorPacket_<ContainerAllocator> Type;

  SensorPacket_()
    : sns_1_FFT_NS()
    , sns_1_FFT_WE()
    , sns_1_4Ch()
    , sns_1_F_M()
    , sns_2_FFT_NS()
    , sns_2_FFT_WE()
    , sns_2_4Ch()
    , sns_2_F_M()
    , sns1_vorticity(0.0)
    , sns2_vorticity(0.0)  {
    }
  SensorPacket_(const ContainerAllocator& _alloc)
    : sns_1_FFT_NS(_alloc)
    , sns_1_FFT_WE(_alloc)
    , sns_1_4Ch(_alloc)
    , sns_1_F_M(_alloc)
    , sns_2_FFT_NS(_alloc)
    , sns_2_FFT_WE(_alloc)
    , sns_2_4Ch(_alloc)
    , sns_2_F_M(_alloc)
    , sns1_vorticity(0.0)
    , sns2_vorticity(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _sns_1_FFT_NS_type;
  _sns_1_FFT_NS_type sns_1_FFT_NS;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _sns_1_FFT_WE_type;
  _sns_1_FFT_WE_type sns_1_FFT_WE;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _sns_1_4Ch_type;
  _sns_1_4Ch_type sns_1_4Ch;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sns_1_F_M_type;
  _sns_1_F_M_type sns_1_F_M;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _sns_2_FFT_NS_type;
  _sns_2_FFT_NS_type sns_2_FFT_NS;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _sns_2_FFT_WE_type;
  _sns_2_FFT_WE_type sns_2_FFT_WE;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _sns_2_4Ch_type;
  _sns_2_4Ch_type sns_2_4Ch;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _sns_2_F_M_type;
  _sns_2_F_M_type sns_2_F_M;

   typedef float _sns1_vorticity_type;
  _sns1_vorticity_type sns1_vorticity;

   typedef float _sns2_vorticity_type;
  _sns2_vorticity_type sns2_vorticity;





  typedef boost::shared_ptr< ::tae_psoc::SensorPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tae_psoc::SensorPacket_<ContainerAllocator> const> ConstPtr;

}; // struct SensorPacket_

typedef ::tae_psoc::SensorPacket_<std::allocator<void> > SensorPacket;

typedef boost::shared_ptr< ::tae_psoc::SensorPacket > SensorPacketPtr;
typedef boost::shared_ptr< ::tae_psoc::SensorPacket const> SensorPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tae_psoc::SensorPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tae_psoc::SensorPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tae_psoc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tae_psoc': ['/home/wilson/ros_ws_1/src/tae_psoc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tae_psoc::SensorPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tae_psoc::SensorPacket_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tae_psoc::SensorPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tae_psoc::SensorPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tae_psoc::SensorPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tae_psoc::SensorPacket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tae_psoc::SensorPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b42cd8856cf6ff4337fc1ed6207fb9c0";
  }

  static const char* value(const ::tae_psoc::SensorPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb42cd8856cf6ff43ULL;
  static const uint64_t static_value2 = 0x37fc1ed6207fb9c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::tae_psoc::SensorPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tae_psoc/SensorPacket";
  }

  static const char* value(const ::tae_psoc::SensorPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tae_psoc::SensorPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] sns_1_FFT_NS\n"
"uint16[] sns_1_FFT_WE\n"
"int16[] sns_1_4Ch\n"
"float32[] sns_1_F_M\n"
"uint16[] sns_2_FFT_NS\n"
"uint16[] sns_2_FFT_WE\n"
"int16[] sns_2_4Ch\n"
"float32[] sns_2_F_M\n"
"float32 sns1_vorticity\n"
"float32 sns2_vorticity\n"
"\n"
;
  }

  static const char* value(const ::tae_psoc::SensorPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tae_psoc::SensorPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sns_1_FFT_NS);
      stream.next(m.sns_1_FFT_WE);
      stream.next(m.sns_1_4Ch);
      stream.next(m.sns_1_F_M);
      stream.next(m.sns_2_FFT_NS);
      stream.next(m.sns_2_FFT_WE);
      stream.next(m.sns_2_4Ch);
      stream.next(m.sns_2_F_M);
      stream.next(m.sns1_vorticity);
      stream.next(m.sns2_vorticity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tae_psoc::SensorPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tae_psoc::SensorPacket_<ContainerAllocator>& v)
  {
    s << indent << "sns_1_FFT_NS[]" << std::endl;
    for (size_t i = 0; i < v.sns_1_FFT_NS.size(); ++i)
    {
      s << indent << "  sns_1_FFT_NS[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.sns_1_FFT_NS[i]);
    }
    s << indent << "sns_1_FFT_WE[]" << std::endl;
    for (size_t i = 0; i < v.sns_1_FFT_WE.size(); ++i)
    {
      s << indent << "  sns_1_FFT_WE[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.sns_1_FFT_WE[i]);
    }
    s << indent << "sns_1_4Ch[]" << std::endl;
    for (size_t i = 0; i < v.sns_1_4Ch.size(); ++i)
    {
      s << indent << "  sns_1_4Ch[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.sns_1_4Ch[i]);
    }
    s << indent << "sns_1_F_M[]" << std::endl;
    for (size_t i = 0; i < v.sns_1_F_M.size(); ++i)
    {
      s << indent << "  sns_1_F_M[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sns_1_F_M[i]);
    }
    s << indent << "sns_2_FFT_NS[]" << std::endl;
    for (size_t i = 0; i < v.sns_2_FFT_NS.size(); ++i)
    {
      s << indent << "  sns_2_FFT_NS[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.sns_2_FFT_NS[i]);
    }
    s << indent << "sns_2_FFT_WE[]" << std::endl;
    for (size_t i = 0; i < v.sns_2_FFT_WE.size(); ++i)
    {
      s << indent << "  sns_2_FFT_WE[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.sns_2_FFT_WE[i]);
    }
    s << indent << "sns_2_4Ch[]" << std::endl;
    for (size_t i = 0; i < v.sns_2_4Ch.size(); ++i)
    {
      s << indent << "  sns_2_4Ch[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.sns_2_4Ch[i]);
    }
    s << indent << "sns_2_F_M[]" << std::endl;
    for (size_t i = 0; i < v.sns_2_F_M.size(); ++i)
    {
      s << indent << "  sns_2_F_M[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sns_2_F_M[i]);
    }
    s << indent << "sns1_vorticity: ";
    Printer<float>::stream(s, indent + "  ", v.sns1_vorticity);
    s << indent << "sns2_vorticity: ";
    Printer<float>::stream(s, indent + "  ", v.sns2_vorticity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAE_PSOC_MESSAGE_SENSORPACKET_H
